Add ip discovery
tuna2134/twilight-audio pull request #3
Opened 2024-08-31 09:08 UTC by tuna2134

2024-08-31 22:46 UTC, tasuren requested changes

2024-08-31 22:46 UTC, tasuren commented on src/voice.rs
> +        buffer[4..6].copy_from_slice(&ssrc.to_be_bytes());
SSRCって4バイトって書いてたけど、これ`buffer[4..6]`ってu8二個分だから2バイトしかないから、SSRC入らないんじゃないかな？
それと、IPディスカバリのパケット作るためのものがDiscoRTPにあったから、それ使っても良いかも。多分RTPでそのライブラリいつか使うだろうし。

2024-08-31 22:46 UTC, tasuren commented on src/voice.rs
> +        };
これってなんでループしているの？今の状態はループしなさそうだけど、将来的にダメだったらリトライするようにしようと思っている？

2024-09-01 00:34 UTC, tuna2134 commented on src/voice.rs
> +        buffer[4..6].copy_from_slice(&ssrc.to_be_bytes());
うーん、ライブラリ使うのか
そうするか

2024-09-01 00:34 UTC, tuna2134 commented on src/voice.rs
> +        };
そそ

2024-09-01 00:35 UTC, tasuren commented on src/voice.rs
> +        };
Ohk

2024-09-01 01:48 UTC, merged